In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import mutual_info_classif
from sklearn.inspection import permutation_importance
from sklearn.feature_selection import RFECV
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
%matplotlib inline

In [3]:
train = pd.read_pickle('../datos/procesados/train_transformado.pkl')

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28402 entries, 1 to 32580
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   calificacion_prestamo                 28402 non-null  float64
 1   incumplimiento_historial              28402 non-null  int64
 2   edad                                  28402 non-null  float64
 3   ingreso                               28402 non-null  float64
 4   duracion_empleo                       28402 non-null  float64
 5   monto_prestamo                        28402 non-null  float64
 6   tasa_interes                          28402 non-null  float64
 7   estado_prestamo                       28402 non-null  int64
 8   porcentaje_ingreso                    28402 non-null  float64
 9   duracion_credito                      28402 non-null  float64
 10  propiedad_vivienda_MORTGAGE           28402 non-null  float64
 11  propiedad_vivienda_OWN                28402 non-null  float64
 12  propiedad_vivienda_RENT               28402 non-null  float64
 13  intencion_prestamo_DEBTCONSOLIDATION  28402 non-null  float64
 14  intencion_prestamo_EDUCATION          28402 non-null  float64
 15  intencion_prestamo_HOMEIMPROVEMENT    28402 non-null  float64
 16  intencion_prestamo_MEDICAL            28402 non-null  float64
 17  intencion_prestamo_PERSONAL           28402 non-null  float64
 18  intencion_prestamo_VENTURE            28402 non-null  float64
dtypes: float64(17), int64(2)
memory usage: 4.3 MB

# Preselcción de variables

### Mutual selector

In [5]:
x = train.drop(columns=['estado_prestamo'])
y = train['estado_prestamo']

In [6]:
def ranking_mi(mutual_selector, modo = 'tabla'):
    #Maqueta el ranking
    ranking_mi = pd.DataFrame(mutual_selector, index = x.columns).reset_index()
    ranking_mi.columns = ['variable','importancia_mi']
    ranking_mi = ranking_mi.sort_values(by = 'importancia_mi', ascending = False)
    ranking_mi['ranking_mi'] = np.arange(0,ranking_mi.shape[0])
    #Muestra la salida
    if modo == 'tabla':
        return(ranking_mi)
    else:
        g = ranking_mi[0:15].importancia_mi.sort_values().plot.barh()
        g.set_yticklabels(ranking_mi[0:15].sort_values(by = 'importancia_mi').variable)
        return(g)

In [7]:
mutual_selector = mutual_info_classif(x,y)
ranking_mi(mutual_selector)

                                variable  importancia_mi  ranking_mi
3                                ingreso        0.108658           0
7                     porcentaje_ingreso        0.081439           1
0                  calificacion_prestamo        0.078559           2
6                           tasa_interes        0.075844           3
11               propiedad_vivienda_RENT        0.032971           4
9            propiedad_vivienda_MORTGAGE        0.018324           5
1               incumplimiento_historial        0.016584           6
5                         monto_prestamo        0.012052           7
10                propiedad_vivienda_OWN        0.007195           8
4                        duracion_empleo        0.006898           9
14    intencion_prestamo_HOMEIMPROVEMENT        0.003960          10
13          intencion_prestamo_EDUCATION        0.003867          11
17            intencion_prestamo_VENTURE        0.003448          12
8                       duracion_credito        0.000486          13
16           intencion_prestamo_PERSONAL        0.000344          14
2                                   edad        0.000277          15
12  intencion_prestamo_DEBTCONSOLIDATION        0.000000          16
15            intencion_prestamo_MEDICAL        0.000000          17

Eliminar las que den 0 ya que no tienen relaciones con la target

In [8]:
train.drop(columns=['edad', 'intencion_prestamo_EDUCATION', 'intencion_prestamo_PERSONAL'], inplace=True)
x.drop(columns=['edad', 'intencion_prestamo_EDUCATION', 'intencion_prestamo_PERSONAL'], inplace=True)

### Correlaciones

In [9]:
def correlaciones_fuertes(df, lim_inf = 0.3, lim_sup = 1,drop_dupli=True):
    #Calcula la matriz de correlación
    c = df.corr().abs()
    #Lo pasa todo a filas
    c= c.unstack()
    #Pasa el índice a columnas y le pone nombres
    c = pd.DataFrame(c).reset_index()
    c.columns = ['var1','var2','corr']
    #A dataframe, filtra limites y ordena en descendiente
    c = c.loc[(c['corr'] > lim_inf) &  (c['corr'] < lim_sup),:].sort_values(by = 'corr', ascending=False)
    #Desduplica las correlaciones (o no si drop_dupli es False)
    c = c if drop_dupli == False else c.drop_duplicates(subset = ['corr'])
    #Devuelve la salida
    return(c)

In [10]:
correlaciones_fuertes(train)

                            var1                         var2      corr
5          calificacion_prestamo                 tasa_interes  0.933625
155  propiedad_vivienda_MORTGAGE      propiedad_vivienda_RENT  0.856529
71                monto_prestamo           porcentaje_ingreso  0.577814
1          calificacion_prestamo     incumplimiento_historial  0.535475
21      incumplimiento_historial                 tasa_interes  0.500086
66                monto_prestamo                      ingreso  0.424133
6          calificacion_prestamo              estado_prestamo  0.379827
118           porcentaje_ingreso              estado_prestamo  0.378764
39                       ingreso           porcentaje_ingreso  0.375801
101              estado_prestamo                 tasa_interes  0.339792
41                       ingreso  propiedad_vivienda_MORTGAGE  0.334515

Eliminar las correlaciones en base a la información mutua y a las correlaciones fuertes.

In [11]:
train.drop(columns=['calificacion_prestamo','propiedad_vivienda_MORTGAGE'], inplace=True)
x.drop(columns=['calificacion_prestamo','propiedad_vivienda_MORTGAGE'], inplace=True)

In [12]:
correlaciones_fuertes(train)

                        var1                var2      corr
87        porcentaje_ingreso      monto_prestamo  0.577814
4   incumplimiento_historial        tasa_interes  0.500086
17                   ingreso      monto_prestamo  0.424133
89        porcentaje_ingreso     estado_prestamo  0.378764
20                   ingreso  porcentaje_ingreso  0.375801
74           estado_prestamo        tasa_interes  0.339792

### Recursive Feature Elimination

In [13]:
rfe = RFECV(estimator = XGBClassifier(n_jobs = -1, eval_metric='auc'),
            scoring = 'roc_auc',
            n_jobs = -1)

rfe.fit(x,y)

rank_rfe = pd.DataFrame({'variable': x.columns, 'ranking_rfe': rfe.ranking_}).sort_values(by = 'ranking_rfe')
rank_rfe

                                variable  ranking_rfe
1                                ingreso            1
2                        duracion_empleo            1
5                     porcentaje_ingreso            1
4                           tasa_interes            1
7                 propiedad_vivienda_OWN            1
10    intencion_prestamo_HOMEIMPROVEMENT            1
9   intencion_prestamo_DEBTCONSOLIDATION            1
8                propiedad_vivienda_RENT            1
12            intencion_prestamo_VENTURE            1
11            intencion_prestamo_MEDICAL            1
3                         monto_prestamo            2
0               incumplimiento_historial            3
6                       duracion_credito            4

Calificar las variales con RFE y quitar las no principales (distintas a 1)

In [ ]:
train.drop(columns=['incumplimiento_historial','monto_prestamo',"duracion_credito"], inplace=True)
x.drop(columns=['incumplimiento_historial','monto_prestamo',"duracion_credito"], inplace=True)
y.drop(columns=['incumplimiento_historial','monto_prestamo',"duracion_credito"], inplace=True)

### Permutation importance

In [15]:
x = train.drop(columns=['estado_prestamo'])
y = train['estado_prestamo']

xgb = XGBClassifier(n_jobs = -1, eval_metric='auc')

xgb.fit(x,y)

permutacion = permutation_importance(xgb, 
                                     x, y, 
                                     scoring = 'roc_auc',
                                     n_repeats=5, n_jobs = -1)

In [16]:
def ranking_per(predictoras,permutacion):
    ranking_per = pd.DataFrame({'variable': predictoras.columns, 'importancia_per': permutacion.importances_mean}).sort_values(by = 'importancia_per', ascending = False)
    ranking_per['ranking_per'] = np.arange(0,ranking_per.shape[0])
    return(ranking_per)

In [17]:
ranking_per(x, permutacion)

                                variable  importancia_per  ranking_per
2                           tasa_interes         0.139292            0
3                     porcentaje_ingreso         0.134446            1
0                                ingreso         0.111264            2
6                propiedad_vivienda_RENT         0.045525            3
5                 propiedad_vivienda_OWN         0.024975            4
1                        duracion_empleo         0.017432            5
10            intencion_prestamo_VENTURE         0.012736            6
8     intencion_prestamo_HOMEIMPROVEMENT         0.011031            7
9             intencion_prestamo_MEDICAL         0.009613            8
4                       duracion_credito         0.009247            9
7   intencion_prestamo_DEBTCONSOLIDATION         0.008922           10

# Balanceo de clases

In [18]:
train.estado_prestamo.value_counts()

estado_prestamo
0    22242
1     6160
Name: count, dtype: int64

No aplicamos balanceo de clases

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28402 entries, 1 to 32580
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ingreso                               28402 non-null  float64
 1   duracion_empleo                       28402 non-null  float64
 2   tasa_interes                          28402 non-null  float64
 3   estado_prestamo                       28402 non-null  int64
 4   porcentaje_ingreso                    28402 non-null  float64
 5   duracion_credito                      28402 non-null  float64
 6   propiedad_vivienda_OWN                28402 non-null  float64
 7   propiedad_vivienda_RENT               28402 non-null  float64
 8   intencion_prestamo_DEBTCONSOLIDATION  28402 non-null  float64
 9   intencion_prestamo_HOMEIMPROVEMENT    28402 non-null  float64
 10  intencion_prestamo_MEDICAL            28402 non-null  float64
 11  intencion_prestamo_VENTURE            28402 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 2.8 MB

# Exportar el dataset

In [21]:
X = train.drop(columns=['estado_prestamo'])
Y = train['estado_prestamo']

X_train, X_test, y_train, y_test = train_test_split(
    X, Y,
    test_size=0.2,
    stratify=Y,
    random_state=42
)
train.to_pickle('../datos/procesados/train_preseleccionado.pkl')
X_train.to_pickle('../datos/entrenamiento/X_train.pkl')
X_test.to_pickle('../datos/entrenamiento/X_test.pkl')
y_train.to_pickle('../datos/entrenamiento/y_train.pkl')
y_test.to_pickle('../datos/entrenamiento/y_test.pkl')