In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import  roc_auc_score

In [12]:
X_train = pd.read_pickle('../datos/entrenamiento/X_train.pkl')
X_test = pd.read_pickle('../datos/entrenamiento/X_test.pkl')
y_train = pd.read_pickle('../datos/entrenamiento/y_train.pkl')
y_test = pd.read_pickle('../datos/entrenamiento/y_test.pkl')

In [13]:
lgbm = HistGradientBoostingClassifier()

lgbm.fit(X_train, y_train)

lgbm_pred = lgbm.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, lgbm_pred))

lgbm_train_pred = lgbm.predict_proba(X_train)[:, 1]
print(roc_auc_score(y_train, lgbm_train_pred))

0.9338296842788276
0.960382586289698

In [14]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

metricas_cv = cross_val_score(estimator=lgbm, 
                              X=X_train, 
                              y=y_train, 
                              cv=skf, 
                              scoring='roc_auc')
print("ROC AUC Score (Cross-Validation):", metricas_cv.mean())

ROC AUC Score (Cross-Validation): 0.9349130219837132

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
grid = {
    'learning_rate': [0.01, 0.05, 0.1],       
    'max_iter': [100, 150, 200],              
    'max_leaf_nodes': [15, 31, 63],            
    'min_samples_leaf': [20, 50, 100],          
    'l2_regularization': [0.0, 1.0, 10.0]       
}
# Configuración del buscador
search = RandomizedSearchCV(
    estimator=lgbm,
    param_distributions=grid,
    n_iter=40,              
    scoring='roc_auc',      
    cv=5,                   
    random_state=42,
    n_jobs=-1              
)

# Ajustar con datos de entrenamiento
search.fit(X_train, y_train)

Mejor combinación: {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}

                                                                                                                params  mean_test_score
39    {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.936473
15    {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.935991
4     {'min_samples_leaf': 50, 'max_leaf_nodes': 31, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.935769
29    {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.935454
18     {'min_samples_leaf': 20, 'max_leaf_nodes': 31, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 0.0}         0.935079
27     {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 0.0}         0.934737
6   {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 10.0}         0.934732
3     {'min_samples_leaf': 50, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.934523
7      {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.934205
2     {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.934184

In [16]:
print('Mejor combinación:' , search.best_params_)

pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', 1000)
pd.DataFrame(search.cv_results_)[['params', 'mean_test_score']].sort_values('mean_test_score', ascending = False)

Mejor combinación: {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}

                                                                                                                params  mean_test_score
39    {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.936473
15    {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.935991
4     {'min_samples_leaf': 50, 'max_leaf_nodes': 31, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.935769
29    {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.935454
18     {'min_samples_leaf': 20, 'max_leaf_nodes': 31, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 0.0}         0.935079
27     {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 0.0}         0.934737
6   {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 10.0}         0.934732
3     {'min_samples_leaf': 50, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.934523
7      {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.934205
2     {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.934184
33     {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 100, 'learning_rate': 0.1, 'l2_regularization': 0.0}         0.934169
16   {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.933862
20    {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 0.0}         0.933586
12   {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 150, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.933516
30    {'min_samples_leaf': 20, 'max_leaf_nodes': 31, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 1.0}         0.933100
23    {'min_samples_leaf': 20, 'max_leaf_nodes': 31, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 0.0}         0.932984
19    {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 1.0}         0.932697
38    {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 100, 'learning_rate': 0.1, 'l2_regularization': 1.0}         0.932651
35    {'min_samples_leaf': 20, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 1.0}         0.931444
9    {'min_samples_leaf': 100, 'max_leaf_nodes': 31, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 1.0}         0.931075
10    {'min_samples_leaf': 20, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 0.0}         0.930926
37   {'min_samples_leaf': 50, 'max_leaf_nodes': 63, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 10.0}         0.930220
31    {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 100, 'learning_rate': 0.1, 'l2_regularization': 10.0}         0.929865
11  {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.05, 'l2_regularization': 10.0}         0.929605
0     {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.925331
22    {'min_samples_leaf': 20, 'max_leaf_nodes': 15, 'max_iter': 100, 'learning_rate': 0.05, 'l2_regularization': 1.0}         0.924387
17    {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.922644
32    {'min_samples_leaf': 50, 'max_leaf_nodes': 63, 'max_iter': 200, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.922505
36    {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 1.0}         0.921235
1     {'min_samples_leaf': 20, 'max_leaf_nodes': 63, 'max_iter': 100, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.918758
28    {'min_samples_leaf': 20, 'max_leaf_nodes': 31, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 1.0}         0.915168
24  {'min_samples_leaf': 100, 'max_leaf_nodes': 31, 'max_iter': 200, 'learning_rate': 0.01, 'l2_regularization': 10.0}         0.914111
5    {'min_samples_leaf': 50, 'max_leaf_nodes': 31, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 10.0}         0.912956
21    {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.910280
34    {'min_samples_leaf': 20, 'max_leaf_nodes': 15, 'max_iter': 200, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.910267
13  {'min_samples_leaf': 100, 'max_leaf_nodes': 63, 'max_iter': 100, 'learning_rate': 0.01, 'l2_regularization': 10.0}         0.907498
26    {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.906974
8     {'min_samples_leaf': 20, 'max_leaf_nodes': 15, 'max_iter': 150, 'learning_rate': 0.01, 'l2_regularization': 0.0}         0.906969
14    {'min_samples_leaf': 50, 'max_leaf_nodes': 15, 'max_iter': 100, 'learning_rate': 0.01, 'l2_regularization': 1.0}         0.901990
25  {'min_samples_leaf': 100, 'max_leaf_nodes': 15, 'max_iter': 100, 'learning_rate': 0.01, 'l2_regularization': 10.0}         0.900312